### ISSUE TITLE
Could you kindly let me know when you plan to release the code?

### ISSUE THREAD

**Issue by lmylhy** [RuoyuGuo/MDA-Net#1]
Could you kindly let me know when you plan to release the code?

**Comment by RuoyuGuo** [comment]
> Could you kindly let me know when you plan to release the code?

Hi, thank you for your interesting, we are currently improving the readability of the code and will release it in the next month.

**Comment by lmylhy** [comment]
> > Could you kindly let me know when you plan to release the code?
> 
> Hi, thank you for your interesting, we are currently improving the readability of the code and will release it in the next month.

Hi, could you release this code in Nov?

**Comment by RuoyuGuo** [comment]
> > > Could you kindly let me know when you plan to release the code?
> > 
> > 
> > Hi, thank you for your interesting, we are currently improving the readability of the code and will release it in the next month.
> 
> Hi, could you release this code in Nov?

We have released the training code.
